# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField()),
                ('farm_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('farm_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('no_of_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('farm_associated', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('depth', models.FloatField()),
                ('average_yield', models.FloatField()),
            ],
        ),
    ]
