# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0003_auto_20170913_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='farm_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
