# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0004_auto_20170913_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='area',
            new_name='income',
        ),
        migrations.RemoveField(
            model_name='household',
            name='region',
        ),
        migrations.RemoveField(
            model_name='well',
            name='area',
        ),
    ]
