# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=550)),
                ('mobile_no', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('acerage', models.FloatField()),
            ],
        ),
    ]
